### ISSUE TITLE
sia miner dosnt starts at all

### ISSUE THREAD

**Issue by 008** [gacopl/NiceHashMiner#6] opened 2017-06-16 14:27 UTC
[2017-06-16 17:25:39] [INFO] [MiningSession] Current device profits:
	Profits for GPU-c2787d78-7a0a-fda3-5f98-2972b726aed8 (GPU#1 MSI GeForce GTX 1080):
		PROFIT = 7.113040000000	(SPEED = 11000000000000		| NHSMA = 0.00064664)	[ccminer_Sia]
		MOST PROFITABLE ALGO: ccminer_Sia, PROFIT: 7.113040000000

[2017-06-16 17:25:39] [INFO] [MiningSession] PrevStateProfit 0, CurrentProfit 7.11304
[2017-06-16 17:25:39] [INFO] [MiningSession] Current Global profit: 17441.17408000 USD/Day
[2017-06-16 17:25:39] [INFO] [MiningSession] Current Global profit: IS PROFITABLE MinProfit mine always regardless of profit
[2017-06-16 17:25:39] [INFO] [ccminer_NVIDIA-MINER_ID(0)-DEVICE_IDs(NOT_SET)] NEW MINER CREATED
[2017-06-16 17:25:39] [INFO] [ExtraLaunchParametersParser] ExtraLaunch params "" for device UUID GPU-c2787d78-7a0a-fda3-5f98-2972b726aed8
[2017-06-16 17:25:39] [INFO] [ExtraLaunchParametersParser] Final extra launch params parse ""
[2017-06-16 17:25:39] [INFO] [ExtraLaunchParametersParser] DisableAMDTempControl is TRUE, temp control parameters will be ignored
[2017-06-16 17:25:39] [INFO] [ccminer_NVIDIA-MINER_ID(0)-DEVICE_IDs(0)] PidData is NULL _Start: Failed to start process, err=267

(profit is not real just testing)

**Comment by gacopl** [comment] 2017-06-16 14:34
same thing i updated bin.zip re-download should work

**Comment by 008** [comment] 2017-06-16 14:34
tnx

**Comment by 008** [comment] 2017-06-16 14:42
error 0xc000007b

![cuda3](https://user-images.githubusercontent.com/860351/27231386-21c0e10e-52bb-11e7-96ad-1d9e0f5adc25.png)

**Comment by gacopl** [comment] 2017-06-16 14:45
can you try go to bin\ccminer_sia and delete cudart dlls ?

**Comment by 008** [comment] 2017-06-16 14:49
same error
![cuda5](https://user-images.githubusercontent.com/860351/27231706-27ec5256-52bc-11e7-87c1-9dee8a9d9d01.png)

**Comment by gacopl** [comment] 2017-06-16 14:51
ok delete those two dlls too, in bin.zip you have vcredist.exe installer can you install it ?

**Comment by 008** [comment] 2017-06-16 14:54
yes i have
now error MSVCR120.dll

**Comment by gacopl** [comment] 2017-06-16 15:02
in main nicehash folder there is msvcr120.dll copy that one to ccminer_sia folder, sorry but i cannot reproduce, what windows are you using

**Comment by 008** [comment] 2017-06-16 15:05
win10 x64

**Comment by 008** [comment] 2017-06-16 15:07
tnx it runs now

**Comment by gacopl** [comment] 2017-06-16 15:08
so in sia folder just the msvcr you copier from main nhm folder is needed ?

**Comment by 008** [comment] 2017-06-16 15:09
yep
that miner is really less profitible then original with my 1080 asus

**Comment by gacopl** [comment] 2017-06-16 15:13
the sia miner ? what original can you link me to it?

**Comment by 008** [comment] 2017-06-16 15:14
i dont know
but it just less profitible then ANY miner in nicehash with 1080

**Comment by gacopl** [comment] 2017-06-16 15:16
not possible, a lot of people confirmed me it gave them boost when using dualmining or zec, did you went through how-to steps to setup them properly ?

**Comment by 008** [comment] 2017-06-16 15:19
what i have too setup in SIA ? Just run it and its 2.5$/day on my 1080

**Comment by gacopl** [comment] 2017-06-16 15:20
you said ANY, so i thought on each algo you have less profits so the problem with profits is only with SIA ?

**Comment by 008** [comment] 2017-06-16 15:20
yep

**Comment by 008** [comment] 2017-06-16 15:22
do you have 1080 ? Can you tell me DUAL miner -setups ? any dual  less profit for me even with +/-

**Comment by gacopl** [comment] 2017-06-16 15:29
asus gtx1080
pasc -dcri 95
dcr -dcri 200
lbry -dcri 200
sia -dcri 150

**Comment by 008** [comment] 2017-06-16 15:34
tnx
asus -dcri 95    5.8$ vs 6.6$ with ewbf
so... DUAL miners usless...

**Comment by gacopl** [comment] 2017-06-16 15:36
for 1080, for 1070 they work better than ewbf, besides ZEC is overpriced right now, it's worth to set up everything properly, 3 days back zec was not so profitable and nhm was switching to duals even on my 1080's

**Comment by 008** [comment] 2017-06-16 15:37
ok tnx

**Comment by gacopl** [comment] 2017-06-16 15:38
now i get it so you complained that SIA mining is a lot less profitable than others like lbry lyra etc from my release is that right ? that's because sia is undervalued now, it really is best to set up everything and let it choose, profits change on algos, thats why nhm is so awesome i know i always get paid best no matter what is going on with coins on markets

**Comment by 008** [comment] 2017-06-16 15:40
you are right

**Comment by gacopl** [comment] 2017-06-16 15:42
ok closing happy hashin

**Closed as completed by gacopl** 2017-06-16 15:42 UTC
